# Generated by Django 2.1.2 on 2018-11-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tddkApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ('publishOn',)},
        ),
        migrations.AddField(
            model_name='offre',
            name='domaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Type', to='tddkApi.Domaine'),
        ),
        migrations.AddField(
            model_name='offre',
            name='typeoffre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Type', to='tddkApi.TypeOffre'),
        ),
    ]
