# Generated by Django 2.1.2 on 2018-11-21 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tddkApi', '0002_auto_20181113_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Suiveurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
